/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.viettuts.detaiso10.view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import vn.viettuts.detaiso10.entity.Customer;

/**
 *
 * @author Bui Anh Tuan
 */
public class khachhangJPanel extends javax.swing.JPanel {

    DocumentBuilderFactory dbf;
    DocumentBuilder db;
    Document doc;
    String tenfile = "C:\\Users\\Bui Anh Tuan\\OneDrive\\Documents\\New WinRAR archive\\Detaiso10\\src\\main\\java\\XML\\khachhang.xml";
    ArrayList<Customer> khList;
    DefaultTableModel dftm = new DefaultTableModel();
    public void hienthi(){
        try {
            
            try {
                dbf = DocumentBuilderFactory.newInstance();
                db = dbf.newDocumentBuilder();
                doc = db.parse(tenfile);
                NodeList nltenkhachhang = doc.getElementsByTagName("tenkhachhang");
                NodeList nlsodienthoai = doc.getElementsByTagName("sodienthoai");
                NodeList nlngaymua = doc.getElementsByTagName("ngaymua");
                NodeList nlsanpham = doc.getElementsByTagName("sanpham");
                
                khList = new ArrayList<>();
                for (int i = 0; i < nltenkhachhang.getLength(); i++) {
                    Customer kh = new Customer();
                    kh.setTenkhachhang(nltenkhachhang.item(i).getTextContent());
                    kh.setSodienthoai(nlsodienthoai.item(i).getTextContent());
                    kh.setNgaymua(nlngaymua.item(i).getTextContent());
                    kh.setSanphammua(nlsanpham.item(i).getTextContent());

                    khList.add(kh);
                }
                dftm.setColumnCount(0);
                dftm.setRowCount(0);
                
                dftm.addColumn("Tên khách hàng");
                dftm.addColumn("Số điện thoại");
                dftm.addColumn("Ngày mua");
                dftm.addColumn("Sản phẩm");
                
                for(Customer kh : khList){
                    Vector v = new Vector();
                    v.add(kh.getTenkhachhang());
                    v.add(kh.getSodienthoai());
                    v.add(kh.getNgaymua());
                    v.add(kh.getSanphammua());
                    
                    dftm.addRow(v);
                }
                
            } catch (SAXException | IOException ex) {
                Logger.getLogger(khachhangJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(khachhangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public khachhangJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        JpnHoaDon = new javax.swing.JPanel();
        jpntieude = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbtenkh = new javax.swing.JLabel();
        jlbsdt = new javax.swing.JLabel();
        jlbngaymua = new javax.swing.JLabel();
        jlbsanpham = new javax.swing.JLabel();
        jtftenkh = new javax.swing.JTextField();
        jtfsdt = new javax.swing.JTextField();
        jtfngaymua = new javax.swing.JTextField();
        jtfsanpham = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Số điện thoại", "Ngày mua", "Sản phẩm"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        JpnHoaDon.setBackground(new java.awt.Color(204, 255, 204));

        jpntieude.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Hóa đơn");

        javax.swing.GroupLayout jpntieudeLayout = new javax.swing.GroupLayout(jpntieude);
        jpntieude.setLayout(jpntieudeLayout);
        jpntieudeLayout.setHorizontalGroup(
            jpntieudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntieudeLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jpntieudeLayout.setVerticalGroup(
            jpntieudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpntieudeLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
        );

        jlbtenkh.setText("Tên khách hàng:");

        jlbsdt.setText("Số điện thoại:");

        jlbngaymua.setText("Ngày mua: ");

        jlbsanpham.setText("Sản phẩm: ");

        jtfsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfsdtActionPerformed(evt);
            }
        });

        jtfsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfsanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnHoaDonLayout = new javax.swing.GroupLayout(JpnHoaDon);
        JpnHoaDon.setLayout(JpnHoaDonLayout);
        JpnHoaDonLayout.setHorizontalGroup(
            JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpntieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JpnHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbsdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbtenkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbngaymua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtftenkh)
                    .addComponent(jtfsdt)
                    .addComponent(jtfngaymua, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfsanpham))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        JpnHoaDonLayout.setVerticalGroup(
            JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnHoaDonLayout.createSequentialGroup()
                .addComponent(jpntieude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbtenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtftenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbngaymua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfngaymua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(JpnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JpnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfsdtActionPerformed

    private void jtfsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfsanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfsanphamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbngaymua;
    private javax.swing.JLabel jlbsanpham;
    private javax.swing.JLabel jlbsdt;
    private javax.swing.JLabel jlbtenkh;
    private javax.swing.JPanel jpntieude;
    private javax.swing.JTextField jtfngaymua;
    private javax.swing.JTextField jtfsanpham;
    private javax.swing.JTextField jtfsdt;
    private javax.swing.JTextField jtftenkh;
    // End of variables declaration//GEN-END:variables
}
